### ISSUE TITLE
need better triangulation

### ISSUE THREAD

**Issue by aferust** [mcodegeeks/PRKit-JS#1]
Please replace triangulation algorithm with this one: https://github.com/mapbox/earcut. In my experiments, this library failed drawing some complex concave polygons with existing triangulation method. Then I modified PRFilledPolygon.js to work with earcut, and It worked flawlessly.

Although I am not familiar with git mechanism (how to pull/push new code etc.), here is my modification that works perfectly:

earcut returns indices. so we need to arrange returning array:
Maybe it is better to implement this function as a private method of cc.PRFilledPolygon. If I am saying something very stupid, sorry I am very new to js :D

```
function triangulate4pr(data){
    var triangles = earcut(data);
    var result = [];
    for(i=0; i<triangles.length; i++){
        result.push(data[2*triangles[i]]);
        result.push(data[2*triangles[i]+1]);

    }
    return result;
}
``` 

and then in PRFilledPolygon.js:
replace this line:
`cc.Triangulate.Process ( Verts, this.Points );`
with this one:
`this.Points = triangulate4pr(Verts);`

**Comment by yhmun** [comment]
Thank you for your contribution. I haven't realized someone who looks at my codes. In this result, I am really happy and appreciated about it and it inspires me to re-walk on sharing some.

**Comment by aferust** [comment]
Hi my friend,

It would be also very good if the library could work with recent version of
cocos2d-x.
